name: "Bug report"
description: "Create a report to help us improve"
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: "Bug description"
      description: "Describe the issue, including steps to reproduce it. Add screenshots if useful."
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: "OS version"
      description: "Example: Ubuntu 22.04, macOS 14.0, Windows 11"
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: "App version"
      description: "Find this in the About page of the app."
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: "RLN node connection type"
      options:
        - Embedded
        - Remote
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: "Bitcoin network"
      options:
        - Regtest
        - Testnet
    validations:
      required: true

  - type: dropdown
    id: installation_method
    attributes:
      label: "Installation method"
      options:
        - AppImage/DMG
        - From source
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs and debug data"
      description: "Attach the app data directory (location can be found in the About page) and any relevant console logs."
      placeholder: "Drag and drop data directory and paste relevant console logs if any."
    validations:
      required: false
